### ISSUE TITLE
.yaml file tag that used to define include path for assembly (Asm) files.

### ISSUE THREAD

**Issue by ozersa** [ARMmbed/DAPLink#1001]
In .yaml file I need to set include folder for assembly files (see below screenshot), but I do not know which tag need to be used for this purpose. 
The below ones does not work, could you let me know which tag use for this purpose?

![image](https://user-images.githubusercontent.com/46590392/215751588-86f8581a-6728-4d90-ad08-44c5547138b3.png)

**Comment by mathias-arm** [comment]
Have you tried something like:
```
tool_specific:
    uvision:
        misc:
            asm_flags:
                - xxx
```

I think [m48ssidae.yaml](https://github.com/ARMmbed/DAPLink/blob/main/records/hic_hal/m48ssidae.yaml#L26) is doing what you are looking to do.
